---
title: "Examining environmental drivers on greenhouse gas fluxes in a constructed stormwater wetland (aka 2017 CSW)"
author: "Gina Bledsoe, Ariane Peralta"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: null
  fig_caption: yes
  html_document: default
editor_options:
  chunk_output_type: console
---
Project Description: Analysis of monthly greenhouse gas fluxes in a constructed stormwater wetland (Greenville, NC, USA).
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r setup workspace}
if(Sys.info()[1] == "Darwin"){
  setwd("~/GitHub/ConstructedStormwaterWetland/analyses/")
} else {
  # setwd(choose.dir())
}
rm(list = ls())

library(ggplot2)
library(psych)
```

```{r read in data}
#GHG Flux data
ghg <- read.csv("../data/CSW_GHG_Env.csv", header=T)
```

```{r normality check, echo=FALSE}
#Used describe to look a skew and kurtosis
#skew - a measure of distibution symmetry, negative is left skew, positive is right skew. Where is the #majority of variaiton located.
#kurtosis - heavy tail (outliers) or light tail (lack of outliers). low = light, high = heavy
describe(ghg, na.rm=F, range=F)
describeBy(ghg, group="hydrology", mat=F, digit=3, na.rm=F, range=F)

#The standard deviations of CO2, CH4, and N2O flux is high indicating variation among plots. 
#N2O is slightly left skewed and CO2 and CH4 are slightly right skewed.
#High kurtosis values indicate outliers in all three GHG

#Shapiro Wilks test of normality
#normality is rejected when the p-value is <= 0.05 
result <- shapiro.test(ghg$ch4.mgm2hr)
result
result <- shapiro.test(ghg$co2.mgm2hr)
result
result <- shapiro.test(ghg$n2o.mgm2hr)
result

#Based on the above the GHG flux data are not normally distributed
#Log transform data response variables
```

```{r axes labels, include=TRUE}
#extra info for graphing
library(scales)
fancy_scientific <- function(l) {
     # turn in to character string in scientific notation
     l <- format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
} #scale_y_continuous(labels=fancy_scientific) 

fmt_decimals <- function(decimals=0){
    function(x) format(x,nsmall = decimals,scientific = FALSE)
} #scale_y_continuous(labels = fmt_decimals(2))
```

```{r CH4 models, echo=T, out.width="100%"}
#sets plots for 2 rows, 2 columns
par(mfcol=c(2,2))

#linear models for CH4
ch4.lm <- lm(log(ch4.mgm2hr)~soiltemp*hydrology*placement, data=ghg)
plot(ch4.lm)
anova(ch4.lm)

p <- ggplot(ghg, aes(x=soiltemp, y=log(ch4.mgm2hr), color=as.factor(hydrology))) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor =element_blank(), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "black",size=1)) + scale_color_manual(name="Hydrology", values=c("darkgray", "blue"), labels = c("shallow (t)", "inundated (w)")) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.75)) 
p1=p+geom_smooth(method="lm")+facet_wrap(~placement)
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Soil Temperature (°C) ", y =  (expression(paste("log CH"[4]," flux (mg m"^-{2},"hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))+theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14))

ggsave("../figures/methane.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r CO2 models, echo=T, out.width="100%"}
#sets plots for 2 rows, 2 columns
par(mfcol=c(2,2))

#linear models for CH4
co2.lm <- lm(log(co2.mgm2hr)~soiltemp*hydrology*placement, data=ghg)
plot(co2.lm)
anova(co2.lm)

p <- ggplot(ghg, aes(x=soiltemp, y=log(co2.mgm2hr), color=as.factor(hydrology))) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor =element_blank(), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "black",size=1)) + scale_color_manual(name="Hydrology", values=c("darkgray", "blue"), labels = c("shallow (t)", "inundated (w)")) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.75)) 
p1=p+geom_smooth(method="lm")+facet_wrap(~placement)
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Soil Temperature (°C) ", y =  (expression(paste("log CO"[2]," flux (mg m"^-{2},"hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))+theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14))

ggsave("../figures/carbondioxide.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r N2O models, echo=T, out.width="100%"}
#sets plots for 2 rows, 2 columns
par(mfcol=c(2,2))

#linear models for CH4
n2o.lm <- lm(log(n2o.mgm2hr)~soiltemp*hydrology*placement, data=ghg)
plot(n2o.lm)
anova(n2o.lm)

p <- ggplot(ghg, aes(x=soiltemp, y=log(n2o.mgm2hr), color=as.factor(hydrology))) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor =element_blank(), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "black",size=1)) + scale_color_manual(name="Hydrology", values=c("darkgray", "blue"), labels = c("shallow (t)", "inundated (w)")) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.75)) 
p1=p+geom_smooth(method="lm")+facet_wrap(~placement)
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Soil Temperature (°C) ", y =  (expression(paste("log ","N"[2],"O"," flux (mg m"^-{2},"hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))+theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14))

ggsave("../figures/nitrousoxide.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```