---
title: Examining environmental drivers on greenhouse gas production and denitrification
  potential in a constructed stormwater wetland (aka 2017 CSW)
author: "Regina B. Bledsoe, Ariane L. Peralta"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
#output:
  #pdf_document: null
  #editor_options: null
  #fig_caption: yes
  #html_document: default
  #word_document: default
  #chunk_output_type: 
---
Project Description: Analysis of seasonal denitrification potential and greenhouse gas production in a constructed stormwater wetland (Greenville, NC, USA).

```{r setup, include=FALSE}
#clears R environment
rm(list = ls())
#use to set global options for chunks e.g., echo and warning options will be applied to all chuncks
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
#use to set working directory 
knitr::opts_knit$set(root.dir="../GitHub/ConstructedStormwaterWetland/analyses")
#list.files()
```

```{r setup load packages}
getwd()
#Set source R tools
source("../bin/DiversityFunctions.R")
source("../bin/MothurTools.R")
#load requires packages
require("ggplot2")
require("psych")
require("dplyr")
require("tidyverse")
require("agricolae")
require("vegan")
require("reshape2") #need for pcoa
require("labdsv")
require("phyloseq")
require("lme4")
require("car")
require("MASS")
require("lindia")

#BiocManager::install("phyloseq")

#Set Std Err and Conf Int
se <- function(x, ...) {
  sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
}
ci <- function(x, ...) {
  1.96 * sd(x, na.rm = TRUE)
}
cbrt<- function(x) { sign(x) * abs(x)^1/3 
  }
set.seed(42)

```

```{r read in ghg and environmental data}
#getwd()

#ghg flux data. measured values
ghg <- read.csv("../data/CSW_GHG_Flux.csv", header=T)
#design data. categorical values ans soil measurements
design <-read.csv("../data/CSW_field_design_soil.csv", header=T)
#water nutrient data 
water <- read.csv("../data/CSW_Water_nutes.csv")

#ghg flux is calcualted from 4 timepoints. first we need to remove lines without flux calcuations. 
ghg <- ghg[,-c(3:4,6:14)]
ghg <- filter(ghg, !is.na(ghg$ch4cgm2day))
#now can combine design and ghg datasets
ghg <- cbind(ghg, design)

#Add calculated fields
ghg <- mutate(ghg, 
      co2ch4=ghg$ch4cmgm2day/ghg$co2cmgm2day, #ch4:co2 ratio   
      ch4co2eq=ghg$ch4cmgm2day*25, #methane carbon dioxide equivalents
      n2oco2eq=ghg$n2onmgm2day*298 #nitrous oxide carbon dixode equivalents
      )
```

```{r plot formatting}
colman <- c("blue","chartreuse4")
hydro_label <- c("flooded wetland", "upland")
season_label <- c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter")
colseason <- c("brown","orange","green4","navyblue") #changed color order follows f, sm, sp, w
```

```{r GHG summary}
#I want to know if hydrology, season, distance.m (from inlet to outlet), or num.days.last.rain has the greatest influence on CH4, CO2, and N2O fluxes from the wetland

#Coverted distance.m to categorical factor, it is the same each sampling
#inlet:1w, 6t, 7t  #middle:2w, 3w, 8t, 9t, 10t    outlet: 4w, 5w, 11t, 12t, 13t   #upland 14t, 15t

#Quick Data Summary
ghg.summary <- ghg %>%
  group_by(hydrology)%>%
  dplyr::summarise(mean_ch4cmgm2hr=mean(ch4cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_co2cmgm2hr=mean(co2cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_n2onmgm2hr=mean(n2onmgm2hr), sd_n2onmgm2hr=sd(n2onmgm2hr))

ghg.summary

ghg.summary <- ghg %>%
  group_by(hydrology, num.days.last.rain)%>%
  dplyr::summarise(mean_ch4cmgm2hr=mean(ch4cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_co2cmgm2hr=mean(co2cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_n2onmgm2hr=mean(n2onmgm2hr), sd_n2onmgm2hr=sd(n2onmgm2hr))

ghg.summary

ghg.summary <- ghg %>%
  group_by(hydrology, distance.bin)%>%
  dplyr::summarise(mean_ch4cmgm2hr=mean(ch4cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_co2cmgm2hr=mean(co2cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_n2onmgm2hr=mean(n2onmgm2hr), sd_n2onmgm2hr=sd(n2onmgm2hr))

ghg.summary

ghg.summary <- ghg %>%
  group_by(hydrology, season)%>%
  dplyr::summarise(mean_ch4cmgm2hr=mean(ch4cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_co2cmgm2hr=mean(co2cmgm2hr), sd_co2cmgm2hr=sd(co2cmgm2hr),mean_n2onmgm2hr=mean(n2onmgm2hr), sd_n2onmgm2hr=sd(n2onmgm2hr))

ghg.summary
```
```{r CH4 Quick visualization} 
#Mike suggested violin plots so I gave it a go and they were very squished
#####Why are they so squished? 
ggplot(aes(x=sampleid, y=ch4cmgm2hr, color=hydrology), data=ghg)+
  geom_violin(trim=FALSE) +
  facet_grid(~season)
#sqrt seems to unsquish them bit
ggplot(aes(x=sampleid, y=cbrt(ch4cmgm2hr), color=hydrology), data=ghg)+
  geom_violin(trim=FALSE)+
  facet_grid(~season)
#maybe boxplots are not so bad in this case?
ggplot(aes(x=sampleid, y=ch4cmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()+
  facet_grid(~season)
ggplot(aes(x=sampleid, y=ch4cmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()
```

```{r CH4 Do we have normaility?}
#First check the distibution of residuals --- not so great
ch4.lm <- lmer(ch4cmgm2hr~(1|sampleid), data=ghg, REML=TRUE)
summary(ch4.lm, ddf="Kenward-Roger")
confint(ch4.lm)
p=profile(ch4.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(ch4.lm), main="QQ Plot")
shapiro.test(resid(ch4.lm))

#Try cuberoot - works with negative values
#This decreased variance in random effects, CI not 0, but still not normal or is it? 
ch4.lm <- lmer((ch4cmgm2hr)^(1/3)~(1|sampleid), data=ghg, REML=TRUE)
summary(ch4.lm, ddf="Kenward-Roger")
confint(ch4.lm)
p=profile(ch4.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(ch4.lm), main="QQ Plot")
shapiro.test(resid(ch4.lm))

#Since dataset still not normal... going to try log by first adding a constant to deal with < 0 values
m <- min(ghg$ch4cmgm2hr)
ghg$log.ch4 <- log(1 - m + ghg$ch4cmgm2hr)

ch4.lm <- lmer(log.ch4~(1|sampleid), data=ghg, REML=TRUE)
summary(ch4.lm, ddf="Kenward-Roger")
confint(ch4.lm)
p=profile(ch4.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(ch4.lm), main="QQ Plot")
shapiro.test(resid(ch4.lm))

###Not sure if logging helped. Looks like one of diagnostics is better and one is worse. I will run models with both and see what happens

#boxcox for scaling best transformation
#This tells you what lambda value to scale data too
#Keep getting error. Think needs to be lm instead...

```
```{r Hypothesis testing log}
#Which factor/s (Hydrology, season, distance.bin) help explain GHG production?

#ANOVA is is not best here because it treats each observation as an independent observation but can not account for the randomness from sampling the same location. 
#Each sampling plot is measured for GHG monthly over 1 year (n=12). 

#First I want to compare the randomness to parameters that I think might be influencing the response variable. In this case I want to know if hydrology, distance from the inlet, or season influence method production 
require("blme")

ch4.lm1 <- blmer(log.ch4 ~ (1|sampleid) , data=ghg, REML=FALSE)

ch4.lm2 <- blmer(log.ch4~hydrology + (1|sampleid), data=ghg, REML=TRUE)

ch4.lm3 <- blmer(log.ch4~distance.bin + (1|sampleid), data=ghg, REML=FALSE)

ch4.lm4 <- blmer(log.ch4~hydrology * distance.bin + (1|sampleid), data=ghg, REML=FALSE)

ch4.lm5 <- blmer(log.ch4~season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm6 <- blmer(log.ch4~hydrology * season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm7 <- blmer(log.ch4~distance.bin * season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm8 <- blmer(log.ch4~hydrology * distance.bin * season + (1|sampleid), data=ghg, REML=FALSE)

#This is a liklihood ratio test to get Chi squared value and p-value
anova(ch4.lm1, ch4.lm2, ch4.lm3,ch4.lm4,ch4.lm5, ch4.lm6, ch4.lm7, ch4.lm8)

#My conclusion is that hyrdology is the main factor influencing methane rates within the wetland

#confint 0
summary(ch4.lm2, ddf="Kenward-Roger")
confint(ch4.lm2)
p=profile(ch4.lm2)
xyplot(p)
densityplot(p)
qqPlot(resid(ch4.lm2), main="QQ Plot")
shapiro.test(resid(ch4.lm2))

#Post hoc Tests
#Estimated marginal means - similar to lsmeans, uses t distribution
require("emmeans")
  emmeans(ch4.lm6, list(hydrology ~ season), adjust = "tukey")
#Uses z distribution, tends to output smaller p values with smaller datasets
require("multcomp")
  summary(glht(ch4.lm2, linfct=mcp(hydrology="Tukey")))

```

```{r Hypothesis testing not log}

ch4.lm1 <- lmer(ch4cmgm2hr ~ (1|sampleid) , data=ghg, REML=FALSE)

ch4.lm2 <- lmer(ch4cmgm2hr~hydrology + (1|sampleid), data=ghg, REML=TRUE)

ch4.lm3 <- lmer(ch4cmgm2hr~distance.bin + (1|sampleid), data=ghg, REML=FALSE)

ch4.lm4 <- lmer(ch4cmgm2hr~hydrology+ distance.bin + (1|sampleid), data=ghg, REML=FALSE)

ch4.lm5 <- lmer(ch4cmgm2hr~season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm6 <- lmer(ch4cmgm2hr~hydrology+ season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm7 <- lmer(ch4cmgm2hr~distance.bin+ season+ (1|sampleid), data=ghg, REML=FALSE)

ch4.lm8 <- lmer(ch4cmgm2hr~hydrology+ distance.bin + season + (1|sampleid), data=ghg, REML=FALSE)

#This is a liklihood ratio test to get Chi squared value and p-value
anova(ch4.lm1, ch4.lm2, ch4.lm3,ch4.lm4,ch4.lm5, ch4.lm6, ch4.lm7, ch4.lm8)
```



```{r CO2 Quick visualization} 
ggplot(aes(x=sampleid, y=co2cmgm2hr, color=hydrology), data=ghg)+
  geom_violin(trim=FALSE) +
  facet_grid(~season)
#sqrt seems to unsquish them bit
ggplot(aes(x=sampleid, y=cbrt(co2cmgm2hr), color=hydrology), data=ghg)+
  geom_violin(trim=FALSE)+
  facet_grid(~season)
#maybe boxplots are not so bad in this case?
ggplot(aes(x=sampleid, y=co2cmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()+
  facet_grid(~season)
ggplot(aes(x=sampleid, y=co2cmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()
```

```{r CO2 Do we have normaility?}
#First check the distibution of residuals --- not so great
co2.lm <- lmer(co2cmgm2hr~(1|sampleid), data=ghg, REML=TRUE)
summary(co2.lm, ddf="Kenward-Roger")
confint(co2.lm)
p=profile(co2.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(co2.lm), main="QQ Plot")
shapiro.test(resid(co2.lm))

#Try cuberoot - works with negative values
#This decreased variance in random effects, CI not 0, but still not normal or is it? 
co2.lm <- lmer((co2cmgm2hr)^(1/3)~(1|sampleid), data=ghg, REML=TRUE)
summary(co2.lm, ddf="Kenward-Roger")
confint(co2.lm)
p=profile(co2.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(co2.lm), main="QQ Plot")
shapiro.test(resid(co2.lm))

#Since dataset still not normal... going to try log by first adding a constant to deal with < 0 values
m <- min(ghg$co2cmgm2hr)
ghg$log.co2 <- log(2 - m + ghg$co2cmgm2hr)

co2.lm <- lmer(log.co2~(1|sampleid), data=ghg, REML=TRUE)
summary(co2.lm, ddf="Kenward-Roger")
confint(co2.lm)
p=profile(co2.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(co2.lm), main="QQ Plot")
shapiro.test(resid(co2.lm))

###Not sure if logging helped. Looks like one of diagnostics is better and one is worse. I will run models with both and see what happens

#boxcox for scaling best transformation
#This tells you what lambda value to scale data too
#Keep getting error. Think needs to be lm instead...

```
```{r Hypothesis testing log}
#Which factor/s (Hydrology, season, distance.bin) help explain GHG production?

#ANOVA is is not best here because it treats each observation as an independent observation but can not account for the randomness from sampling the same location. 
#Each sampling plot is measured for GHG monthly over 1 year (n=12). 

#First I want to compare the randomness to parameters that I think might be influencing the response variable. In this case I want to know if hydrology, distance from the inlet, or season influence method production 
require("blme")

co2.lm1 <- blmer(log.co2 ~ (1|sampleid) , data=ghg, REML=FALSE)

co2.lm2 <- blmer(log.co2~hydrology + (1|sampleid), data=ghg, REML=TRUE)

co2.lm3 <- blmer(log.co2~distance.bin + (1|sampleid), data=ghg, REML=FALSE)

co2.lm4 <- blmer(log.co2~hydrology * distance.bin + (1|sampleid), data=ghg, REML=FALSE)

co2.lm5 <- blmer(log.co2~season+ (1|sampleid), data=ghg, REML=FALSE)

co2.lm6 <- blmer(log.co2~hydrology * season+ (1|sampleid), data=ghg, REML=FALSE)

co2.lm7 <- blmer(log.co2~distance.bin * season+ (1|sampleid), data=ghg, REML=FALSE)

co2.lm8 <- blmer(log.co2~hydrology * distance.bin * season + (1|sampleid), data=ghg, REML=FALSE)

#This is a liklihood ratio test to get Chi squared value and p-value
anova(co2.lm1, co2.lm2, co2.lm3,co2.lm4,co2.lm5, co2.lm6, co2.lm7, co2.lm8)

#My conclusion is that hyrdology is the main factor influencing methane rates within the wetland

#confint 0
summary(co2.lm2, ddf="Kenward-Roger")
confint(co2.lm2)
p=profile(co2.lm2)
xyplot(p)
densityplot(p)
qqPlot(resid(co2.lm2), main="QQ Plot")
shapiro.test(resid(co2.lm2))

#Post hoc Tests
#Estimated marginal means - similar to lsmeans, uses t distribution
require("emmeans")
  emmeans(co2.lm6, list(hydrology ~ season), adjust = "tukey")
#Uses z distribution, tends to output smaller p values with smaller datasets
require("multcomp")
  summary(glht(co2.lm2, linfct=mcp(hydrology="Tukey")))
```


```{r n2on Quick visualization} 
ggplot(aes(x=sampleid, y=n2onmgm2hr, color=hydrology), data=ghg)+
  geom_violin(trim=FALSE) +
  facet_grid(~season)
#sqrt seems to unsquish them bit
ggplot(aes(x=sampleid, y=(n2onmgm2hr)^(1/3), color=hydrology), data=ghg)+
  geom_violin(trim=FALSE)+
  facet_grid(~season)
#maybe boxplots are not so bad in this case?
ggplot(aes(x=sampleid, y=n2onmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()+
  facet_grid(~season)
ggplot(aes(x=sampleid, y=n2onmgm2hr, color=hydrology), data=ghg)+
  geom_boxplot()
```

```{r n2on Do we have normaility?}
#First check the distibution of residuals --- not so great
n2on.lm <- lmer(n2onmgm2hr~(1|sampleid), data=ghg, REML=TRUE)
summary(n2on.lm, ddf="Kenward-Roger")
confint(n2on.lm)
p=profile(n2on.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(n2on.lm), main="QQ Plot")
shapiro.test(resid(n2on.lm))

#Try cuberoot - works with negative values
#This decreased variance in random effects, CI not 0, but still not normal or is it? 

c.n2on <- cbrt(ghg$n2onmgm2hr)
n2on.lm <- lmer(((n2onmgm2hr)^(1/3))~(1|sampleid), data=ghg, REML=TRUE)
summary(n2on.lm, ddf="Kenward-Roger")
confint(n2on.lm)
p=profile(n2on.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(n2on.lm), main="QQ Plot")
shapiro.test(resid(n2on.lm))

#Since dataset still not normal... going to try log by first adding a constant to deal with < 0 values
m <- min(ghg$n2onmgm2hr)
ghg$log.n2on <- log(2 - m + ghg$n2onmgm2hr)

n2on.lm <- lmer(log.n2on~(1|sampleid), data=ghg, REML=TRUE)
summary(n2on.lm, ddf="Kenward-Roger")
confint(n2on.lm)
p=profile(n2on.lm)
xyplot(p)
densityplot(p)
qqPlot(resid(n2on.lm), main="QQ Plot")
shapiro.test(resid(n2on.lm))

###Not sure if logging helped. Looks like one of diagnostics is better and one is worse. I will run models with both and see what happens

#boxcox for scaling best transformation
#This tells you what lambda value to scale data too
#Keep getting error. Think needs to be lm instead...

```
```{r Hypothesis testing log}
#Which factor/s (Hydrology, season, distance.bin) help explain GHG production?

#ANOVA is is not best here because it treats each observation as an independent observation but can not account for the randomness from sampling the same location. 
#Each sampling plot is measured for GHG monthly over 1 year (n=12). 

#First I want to compare the randomness to parameters that I think might be influencing the response variable. In this case I want to know if hydrology, distance from the inlet, or season influence method production 
require("blme")

n2on.lm1 <- blmer(log.n2on ~ (1|sampleid) , data=ghg, REML=FALSE)

n2on.lm2 <- blmer(log.n2on~hydrology + (1|sampleid), data=ghg, REML=TRUE)

n2on.lm3 <- blmer(log.n2on~distance.bin + (1|sampleid), data=ghg, REML=FALSE)

n2on.lm4 <- blmer(log.n2on~hydrology * distance.bin + (1|sampleid), data=ghg, REML=FALSE)

n2on.lm5 <- blmer(log.n2on~season+ (1|sampleid), data=ghg, REML=FALSE)

n2on.lm6 <- blmer(log.n2on~hydrology * season+ (1|sampleid), data=ghg, REML=FALSE)

n2on.lm7 <- blmer(log.n2on~distance.bin * season+ (1|sampleid), data=ghg, REML=FALSE)

n2on.lm8 <- blmer(log.n2on~hydrology * distance.bin * season + (1|sampleid), data=ghg, REML=FALSE)

#This is a liklihood ratio test to get Chi squared value and p-value
anova(n2on.lm1, n2on.lm2, n2on.lm3,n2on.lm4,n2on.lm5, n2on.lm6, n2on.lm7, n2on.lm8)

#My conclusion is that hyrdology is the main factor influencing methane rates within the wetland

#confint 0
summary(n2on.lm2, ddf="Kenward-Roger")
confint(n2on.lm2)
p=profile(n2on.lm2)
xyplot(p)
densityplot(p)
qqPlot(resid(n2on.lm2), main="QQ Plot")
shapiro.test(resid(n2on.lm2))

#Post hoc Tests
#Estimated marginal means - similar to lsmeans, uses t distribution
require("emmeans")
  emmeans(n2on.lm4, list(hydrology ~ distance.bin), adjust = "tukey")
#Uses z distribution, tends to output smaller p values with smaller datasets
require("multcomp")
  summary(glht(n2on.lm2, linfct=mcp(hydrology="Tukey")))

```


```{r soil_sediment parameters}
#First sediment parameters. There are GHG fluxes and sediment properties for 4 timepoints (May, Aug, Oct, Dec)
#Filter ghg dataset to include only sampling points with soil variables
ghg.soil <- ghg %>%
  filter(date=="5/18/2017" | date=="7/26/2017" | date=="10/18/2017" | date=="12/14/2017")

#Remove correlated variables first.... fix subsetting
cor(ghg.soil[,-c(1:30)])
correlation()
```

```{r CH4 by season, echo=T, out.width="100%"}
#linear model for methane
i <- with(ghg, interaction(hydrology,season))
ghg.lm <- aov(log10(ch4cmgm2day)~hydrology+season+i,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

t <- HSD.test(ghg.lm, "i", group=TRUE, alpha=0.05)
t
plot(t)

#boxplots
p <- ggplot(ghg, aes(x=season, y=log10(ch4cmgm2day), color=season, shape=hydrology)) + geom_boxplot() +
  geom_point(aes(color=factor(season)), size=2, position = position_jitterdodge()) +
  scale_color_manual(name="Season", values=colseason, labels = season_label) +     
  scale_shape_manual(name="Hydrology", values=c(17,21), labels = hydro_label) +      
  scale_x_discrete(labels=season_label,limits=c("sp", "sm", "f", "w")) + 
  labs(x = "Season", y = (expression(paste("log CH"[4], " (mg C"," m"^-{2}," day"^-{1},")")))) +
  ggtitle("Seasonal Methane Fluxes") +
  #set Tukey groups from HSD.test above
  annotate("text",x=1.2,y=2.5, label="c") +
  annotate("text",x=2.2,y=1.5, label="c") +
  annotate("text",x=3.2,y=1.5, label="c") +
  annotate("text",x=4.2,y=1.5, label="c") +
  annotate("text",x=0.8,y=7, label="bc") +
  annotate("text",x=1.8,y=10, label="a") + 
  annotate("text",x=2.8,y=10, label="b") + 
  annotate("text",x=3.8,y=9, label="bc") + 
  #set plot design
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line =   
          element_line(colour = "black"),axis.title=element_text(size=12,face="bold"), 
          axis.text=element_text(size=12), axis.text.x = element_text(size=12), panel.border = 
          element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm"))
p

ggsave("../figures/CH4bySeason.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r CO2 by season, echo=T, out.width="100%"}
#linear model for methane
i <- with(ghg, interaction(hydrology,season))
ghg.lm <- aov(co2cgm2day~hydrology+season+i,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

t <- HSD.test(ghg.lm, "i", group=TRUE, alpha=0.05)
t
plot(t)

p <- ggplot(ghg, aes(x=season, y=co2cgm2day, color=season, shape=hydrology)) + geom_boxplot() +
  geom_point(aes(color=factor(season)), size=2, position = position_jitterdodge()) +
  scale_color_manual(name="Season", values=colseason, labels = season_label) +     
  scale_shape_manual(name="Hydrology", values=c(17,21), labels = hydro_label) +      
  scale_x_discrete(labels=season_label,limits=c("sp", "sm", "f", "w")) + 
  labs(x = "Season", y = (expression(paste("CO"[2], " (g C"," m"^-{2}," day"^-{1},")")))) +
  ggtitle("Seasonal Carbon Dioxide Fluxes") +
  #set Tukey groups from HSD.test above
  annotate("text",x=0.8,y=5, label="b") +
  annotate("text",x=1.2,y=4, label="b") +
  annotate("text",x=1.8,y=8, label="a") + 
  annotate("text",x=2.2,y=4, label="b") +
  annotate("text",x=2.8,y=4.2, label="b") +
  annotate("text",x=3.2,y=4.2, label="b") + 
  annotate("text",x=3.8,y=4.2, label="b") +
  annotate("text",x=4.2,y=4.2, label="b") + 
  #set plot design
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line =   
          element_line(colour = "black"),axis.title=element_text(size=12,face="bold"), 
          axis.text=element_text(size=12), axis.text.x = element_text(size=12), panel.border = 
          element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm"))
p

ggsave("../figures/CO2bySeason.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r N2O by season, echo=T, out.width="100%"}
#linear model for methane
i <- with(ghg, interaction(hydrology,season))
ghg.lm <- aov(n2ongm2day~hydrology+season+i,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

t <- HSD.test(ghg.lm, "i", group=TRUE, alpha=0.05)
t
plot(t)

p <- ggplot(ghg, aes(x=season, y=n2ongm2day, color=season, shape=hydrology)) + geom_boxplot() +
  geom_point(aes(color=factor(season)), size=2, position = position_jitterdodge()) + 
  scale_color_manual(name="Season", values=colseason, labels = season_label) +     
  scale_shape_manual(name="Hydrology", values=c(17,21), labels = hydro_label) +      
  scale_x_discrete(labels=season_label,limits=c("sp", "sm", "f", "w")) + 
  labs(x = "Season", y = (expression(paste("N"[2],"O", " (g C"," m"^-{2}," day"^-{1},")")))) +
  ggtitle("Seasonal Nitrous Oxide Fluxes") +
  #set Tukey groups from HSD.test above
  #annotate("text",x=0.8,y=0.005, label="b") +
  #annotate("text",x=1.8,y=0.008, label="b") +
  #annotate("text",x=2.8,y=0.005, label="b") +
  #annotate("text",x=3.8,y=0.009, label="b") +
  #annotate("text",x=1.2,y=0.005, label="b") +
  #annotate("text",x=2.2,y=0.007, label="a") + 
  #annotate("text",x=3.2,y=0.005, label="b") + 
  #annotate("text",x=4.2,y=0.005, label="b") + 
  #set plot design
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line =   
          element_line(colour = "black"),axis.title=element_text(size=12,face="bold"), 
          axis.text=element_text(size=12), axis.text.x = element_text(size=12), panel.border = 
          element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm"))
p

ggsave("../figures/N2ObySeason.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```




```{r }
#Which environmental parameters help explain ghg production?
#Have monthly water values that correspond to PI chambers 1w-5w
#Have sediment values for 4 timepoints (May, Aug, Oct, Dec)

#I log used the log to help with normality
require(nlme)
ghg$logch4 <- log(ghg$ch4cmgm2day)
ch4.lm <- lm(logch4~hydrology*season, random=~1|sampleid/hydrology, data=ghg)
plot(ch4.lm)
anova(ch4.lm)
summary(ch4.lm)

ch4.lm <- lm(logch4~hydrology*season+distance.m+num.days.last.rain.+water.depth.cm, random=~1|sampleid/hydrology, data=ghg)
plot(ch4.lm)
anova(ch4.lm)
summary(ch4.lm)

require(car)
outlierTest(ch4.lm)
leveragePlots(ch4.lm)

# Normality of Residuals
# qq plot for studentized resid
qqPlot(ch4.lm, main="QQ Plot")
# distribution of studentized residuals
require(MASS)
sresid <- studres(ch4.lm)
hist(sresid, freq=FALSE,
   main="Distribution of Studentized Residuals")
xfit<-seq(min(sresid),max(sresid),length=40)
yfit<-dnorm(xfit)
lines(xfit, yfit) 



```


```{r }

#Maybe methane and carbon dixoide are highly corrleated especially in flooded plots
g <- ggplot(aes(x=ch4cgm2day, y=co2cgm2day, color = hydrology), data=ghg) +
  geom_point()+
  geom_smooth()

ghg.filter <- ghg %>%
  filter(hydrology=="PI")

corr_spearman <- cor.test(x=ghg.filter$ch4cgm2day, y=ghg.filter$co2cgm2day, method = 'spearman')
corr_spearman 
corr_kendall <- corr <- cor.test(x=ghg.filter$ch4cgm2day, y=ghg.filter$co2cgm2day, method = 'kendall')
corr_kendall
corr_pearson <- corr <- cor.test(x=ghg.filter$ch4cgm2day, y=ghg.filter$co2cgm2day, method = 'pearson')
corr_pearson

```


```{r CO2:CH4  by season, echo=T, out.width="100%"}
#linear model for methane
#remove outlier spring co2_ch4 >8000
ghg.ratio <- subset(ghg, co2_ch4<6000)
i <- with(ghg.ratio, interaction(hydrology,season))
ghg.lm <- aov(co2_ch4~hydrology+season+i,data=ghg.ratio)
plot(ghg.lm)
anova(ghg.lm)
#i <- with(ghg, interaction(hydrology,season))
#ghg.lm <- lm(co2_ch4~hydrology+season+i,data=ghg)
#plot(ghg.lm)
#anova(ghg.lm)

summary(ghg.lm)

t <- HSD.test(ghg.lm, "i", group=TRUE, alpha=0.05)
t
plot(t)

p <- ggplot(ghg.ratio, aes(x=season, y=co2_ch4, color=season, shape=hydrology))+ geom_boxplot() +
  geom_point(aes(color=factor(season)), size=2, position = position_jitterdodge()) +  
  scale_color_manual(name="Season", values=colseason, labels = season_label) +     
  scale_shape_manual(name="Hydrology", values=c(17,21), labels = hydro_label) +      
  scale_x_discrete(labels=season_label,limits=c("sp", "sm", "f", "w")) + 
  labs(x = "Season", y = (expression(paste("CO"[2],": CH"[4])))) +
  ggtitle("Seasonal carbon dioxide:methane ratio") +

  #set plot design
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line =   
          element_line(colour = "black"),axis.title=element_text(size=12,face="bold"), 
          axis.text=element_text(size=12), axis.text.x = element_text(size=12), panel.border = 
          element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm"))
p

ggsave("../figures/co2_ch4Season.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```


```{r read in sequence data}
#Read in design file
meta <- read.csv("../data/CSW_16S_design.csv", row.names=1)
#Read in OTU file
otu <- read.otu("../data/csw2017.opti_mcc_withArchaea.shared")

# Import Taxonomy File
tax <- read.tax(taxonomy = "../data/csw2017.opti_mcc.0.03.cons_withArchaea.taxonomy",
                   format = "rdp", tax.levels = 6, col.tax = 3)

#tax <- read.tax(taxfile)
#read.tax does not work and I was unable to solve issue. I use phyloseq import_mothur as a work around. #there was no 'bin' folder with MothurTools
#tax <- import_mothur(mothur_constaxonomy_file =  taxfile)
tax.df <- as.data.frame(tax)
colnames(tax.df)=c("Domain","Phylum","Class", "Order","Family","Genus")
tax <- tax_table(tax.df)
#tax

#Remove OTUs with less than 2 occurences across all sites
otu.2 <- otu[, which(colSums(otu) > 2)]
#colnames(otu.2)
#rownames(otu.2)

#What sample has lowest read count? 
otu2<- colSums(t(otu.2))
#otu2
otu2[which.min(colSums(t(otu.2)))]
otu2[which.max(colSums(t(otu.2)))]

#graph of read counts, need to work on y axis
c<-as.data.frame(otu.2)
c$colsum <- colSums(t(c))
c$group <- rownames(c)
p<-ggplot(c, aes(x=group,y=colsum))+geom_bar(stat="identity")+coord_flip()
p

#Rarefy
#Set min sample number
min.N <- min(rowSums(otu.2))
#rrarefy returns a randomly rarefied community data frame or vector of selected size
#This is the otu set that should be used for beta diversity metrics
otu.rare <- rrarefy(otu.2, min.N)

```


```{r rarefaction curve}
#rarefy returns a species richness estimate in a random subsample of selected size
otu.rare.rich <- rarefy(x = otu.2, sample=min.N, se=T)
#Plot rarefaction curve
###I am not sure how to interpret this. I think it suggests that I did not capture all of the diversity? AP response: Yes, when the collector's curve is still increasing, then if we sampled more deeply, there would still be new OTUs sampled
rarecurve(x = otu.2, step = 20, col="blue", cex=0.6, las=1)
abline(0,1,col='red')
text(10000,10000,"1:1",pos=2, col='red')

```


```{r Relative abundance and PERMANOVA }
#transforms read counts to relative abundance
#Using rarefied OTU dataset
otu.2.rel <- otu.2
for(i in 1:dim(otu.2)[1]){
  otu.2.rel[i,] <- otu.2[i,]/sum(otu.2[i,])
}

#Combine experimental deisng meta data with OTU relative abundance data
metaotu <- cbind(meta, otu.2.rel)
#Where does otu data begin, remove for PERMANOVA
#metaotu[1:5, c(1:5)]

#PERMANOVA with plant and Treatment as factors
#Among all treatments plant (soil source) and treatment
metaotu.ad <- adonis(metaotu[,-c(1:5)] ~treatment*season, method = "bray", data = metaotu, perm=1000, set.seed=42)
metaotu.ad 

```

```{r Calculate distance matrix and PCoA components }

otu.2.rel.dist<-vegdist(otu.2.rel, method="bray")

# Principal Coordinates Analysis
otu.2.rel.dist.pcoa <- cmdscale(otu.2.rel.dist, k=3, eig=TRUE, add=FALSE)
# Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
# eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1a <- round(otu.2.rel.dist.pcoa$eig[1] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
explainvar2a <- round(otu.2.rel.dist.pcoa$eig[2] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
sum.eiga <- sum(explainvar1a, explainvar2a)

explainvar1a
explainvar2a

```

```{r PCoA Plot }
#all.equal(rownames(meta), rownames(otu.2.rel))
# Set treatments
treat1 <- as.factor(meta$month)
levels(treat1) <- ordered(c("May","October"))
treat2 <- as.factor(meta$treatment)
levels(treat2) <- c("flooded wetland", "upland")

pcoa.groups <- paste(meta$month, meta$treatment, sep = "_")
pcoa.points <- data.frame(otu.2.rel.dist.pcoa$points, group = pcoa.groups)

# Calculate Centroids (mean and SE)
pcoa.L.centroids <- melt(pcoa.points, id="group", measure.vars = c("X1", "X2"))
pcoa.centroids <- acast(pcoa.L.centroids, variable ~ group, mean)
pcoa.centroids.se <- acast(pcoa.L.centroids, variable ~ group, se)
pcoa.centroids.sd <- acast(pcoa.L.centroids, variable ~ group, sd)

# Combine - updated
# Combine
pcoa.cent.dataframe <- cbind(t(pcoa.centroids), t(pcoa.centroids.se))
colnames(pcoa.cent.dataframe) <- c("V1", "V2", "V1e", "V2e")
pcoa.cent.treats <- rownames(pcoa.cent.dataframe)
trt.month <- c("May","May","October","October")
trt.location <- c("flooded wetland", "upland","flooded wetland", "upland")
pcoa.cent.dataframe.trts <- as.data.frame(pcoa.cent.dataframe)
pcoa.cent.dataframe.trts$month <- as.factor(trt.month)
pcoa.cent.dataframe.trts$location <- as.factor(trt.location)

meta.env <- design %>% 
dplyr::select(ddate, month,sampleid, hydrology, season, ph, om.percent, nh4n.mg.gdw, no3n.mg.gdw, c.percent, n.percent, c.n)%>%
  filter(ddate=='5/16/2017' | ddate=='10/15/2017') %>%
  filter(sampleid %in% c('01W', '02W','03W', '04W','05W','07T', '08T','09T','11T', '12T', '13T'))

fit<-envfit(otu.2.rel.dist.pcoa$points, meta.env, perm=1000, na.rm=T, set.seed=42)

A <-as.list(fit$vectors)
vec<-as.data.frame(fit$vectors$arrows*sqrt(fit$vectors$r)*0.35)
p<- as.data.frame(A$pvals)
#vec <- cbind(vec, p) 
#vec <-  subset(vec, A$pvals<=0.05)

#vec$parm<-rownames(vec)
#colnames(vec)

####None of the soil parameters were significant predictors of bacterial community beta diversity

#plot PCoA
df1a <- as.data.frame(pcoa.cent.dataframe.trts)
plot1 <- ggplot(df1a, aes(x=V1, y=V2,  color=location, shape = month),
                 group = interaction(month, location)) + theme_bw()  + 
    geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.02), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.02), colour="black") + 
  geom_point(aes(shape = month, colour = location), size=7) + 
#removes gridlines from plot
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
#Set colors for treatments
  scale_colour_manual(labels = c("flooded wetland", "upland"), 
                    values = c("blue", "chartreuse4")) + 
  scale_shape_manual(labels = c("May", "October"), 
                   values = c(16,15)) +
#Sets map coordinates
  coord_cartesian(xlim = c(-0.3, 0.3), ylim = c(-0.3, 0.3)) +
#Sets axis text and put border around plot
  theme(axis.title = element_text(size=14), 
        axis.text.x = element_text(size=14),  axis.text.y = element_text(size=14),
        panel.border = element_rect(colour = "black", size=1.25)) +
  #Set plot title textsize
  theme(plot.title=element_text(size=14)) +
  #Set legend text size
  theme(legend.text=element_text(size=14), legend.title = element_text(size=14))+
  #Sets size of tick marks on axis
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  #Sets labels for plot title, axis titles, and legend headings
  xlab("PCoA 1 (17.4%)") + ylab("PCoA 2 (13.0%)") + 
  labs(shape = "Month") +
  labs(colour="Location") +
  ggtitle("16S rRNA Microbial Community Composition") 
  
plot1 

#Save a copy of the plot
ggsave("../figures/CSW_PCoA.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=8.7, height=6.3, dpi=900, limitsize=TRUE)

```

#DENITRIFICATION ENZYME ASSAY
```{r read in data}
#CSW DEA data
DEA <- read.csv("../data/CSW_DEA_Env.csv", header=T)
```

```{r DEA with acetylene, echo=T, out.width="100%"}
#linear model for no acetylene/ yes acetylene DEA ratio
DEA.lm <- lm(y.ng.N2ON.hr.gdw~hydrology*season,data=DEA)
plot(DEA.lm)
anova(DEA.lm)
#hydro_label <- c("flooded wetland", "upland")
p <- ggplot(DEA, aes(x=season, y=y.ng.N2ON.hr.gdw, color=as.factor(hydrology), shape=as.factor(hydrology))) +   
      geom_boxplot() + geom_point(aes(color=factor(hydrology)), size=2, position = position_jitterdodge()) +   
      scale_color_manual(name="Hydrology", values=c("blue", "chartreuse4"), labels = hydro_label) + 
      scale_shape_manual(name="Hydrology", values=c(17,21), labels = c("flooded wetland", "upland")) +
      scale_x_discrete(labels=c("1spring" = "spring", "2summer" = "summer", "3fall" = "fall", "4winter" = "winter"))
p1 <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = 
              element_line(colour = "black")) + 
      theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = 
              element_text(vjust=0.65, hjust=0.5, size=16), panel.border = element_rect(colour = "black",size=1)) +   
      theme(axis.ticks.length=unit(0.3,"cm")) + 
      labs(x = "Season", y = (expression(paste("Denitrification Rate (ng N"[2],"O g"^-{1}," DM hr"^-{1},")")))) +   
      theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"),
              strip.background = element_rect(colour="black", fill="white", size=1)) +
      theme(legend.title=element_text(size=14),legend.text=element_text(size=14))
p1

ggsave("../figures/DEApotential.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r DEA with no acetylene, echo=T, out.width="100%"}
#linear model for no acetylene/ yes acetylene DEA ratio
DEA.lm <- lm(n.ng.N2ON.hr.gdw~hydrology*season,data=DEA)
plot(DEA.lm)
anova(DEA.lm)

p <- ggplot(DEA, aes(x=season, y=n.ng.N2ON.hr.gdw, color=as.factor(hydrology), shape=as.factor(hydrology))) + 
      geom_boxplot() + geom_point(aes(color=factor(hydrology)), size=2, position = position_jitterdodge())  + 
      scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = hydro_label) + 
      scale_shape_manual(name="Hydrology", values=c(17,21), labels = c("flooded wetland", "upland")) + 
      scale_x_discrete(labels=c("1spring" = "spring", "2summer" = "summer", "3fall" = "fall", "4winter" = "winter"))
p1 <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Season", y = (expression(paste("Denitrification Rate (ng N"[2],"O g"^-{1}," DM hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))+ theme(legend.title=element_text(size=14),legend.text=element_text(size=14))
p1

ggsave("../figures/DEApotential_NOacetylene.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)

```

```{r DEA ratio, echo=T, out.width="100%"}
#linear model for no acetylene/ yes acetylene DEA ratio
ratio.lm <- lm(rN2O_N2O.N2~hydrology*season,data=DEA)
plot(ratio.lm)
anova(ratio.lm)

p <- ggplot(DEA, aes(x=season, y=rN2O_N2O.N2, color=as.factor(hydrology), shape=as.factor(hydrology))) +
      geom_boxplot() + geom_point(aes(color=factor(hydrology)), size=2, position = position_jitterdodge()) + 
      scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = hydro_label) + 
      scale_shape_manual(name="Hydrology", values=c(17,21), labels = hydro_label) + 
      scale_x_discrete(labels=c("1spring" = "spring", "2summer" = "summer", "3fall" = "fall", "4winter" = "winter"))
p1 <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = 
              element_line(colour = "black")) +
      theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=18), axis.text.x = 
              element_text(vjust=0.65, hjust=0.5, size=18), panel.border = element_rect(colour = "black",size=1)) + 
      theme(axis.ticks.length=unit(0.3,"cm")) + 
              labs(x = "Season", y = (expression(paste("rate(N"[2],"O)/rate(N"[2],"O+N"[2],")")))) + 
      theme(strip.text.x = element_text(size=18, face="bold"), 
              strip.text.y = element_text(size=18, face="bold"), 
              strip.background = element_rect(colour="black", fill="white", size=1)) +   
      theme(legend.title=element_text(size=14),legend.text=element_text(size=14))
p1

ggsave("../figures/DEAratio.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r DEA with acetylene by sample plot, echo=T, out.width="100%"}
#linear model for no acetylene/ yes acetylene DEA ratio
DEA.lm <- lm(y.ng.N2ON.hr.gdw~sample*season,data=DEA)
plot(DEA.lm)
anova(DEA.lm)

p <- ggplot(DEA, aes(x=sample, y=n.ng.N2ON.hr.gdw, color=as.factor(hydrology), shape=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=0.75, position=position_dodge(width=0.3)) + scale_color_manual(name="Hydrology", values=c("darkgreen","navy"), labels = c("terrestrial", "inundated")) + scale_shape_manual(name="Hydrology", values=c(16,17), labels = c("terrestrial", "inundated")) +facet_wrap(~season) 
p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=8), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("Denitrification Rate (ng N"[2],"O g"^-{1}," DM hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))+ theme(legend.title=element_text(size=14),legend.text=element_text(size=14))

ggsave("../figures/DEApotential_location.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r load taxonomy data into phyloseq object}
# Import otu and tax into phyloseq
otu <- otu_table(t(otu.2), taxa_are_rows = T)
#tax <- import_mothur(mothur_constaxonomy_file =  taxfile)
#rownames(meta) <- meta$group
sample <- sample_data(meta)
#import into phyloseq
phy<-phyloseq(otu,tax) #################################ERROR  
  #invalid class “phyloseq” object: 
  #Component taxa/OTU names do not match
row.names(sample)=meta$Group
sample_names(sample)
#Assign rownames to be Sample ID's
# Merge mothurdata object with sample metadata
meta_merge <- merge_phyloseq(phy,sample_names)

#meta_merge

#assign column names
colnames(tax_table(meta_merge))
colnames(tax_table(meta_merge)) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")
colnames(tax_table(meta_merge))
rank_names(meta_merge)

#Inspecting phyloseq object
#sample_variables(meta_merge)
#sample_names(meta_merge)
#tax_table(meta_merge)[1:5, 2:6]

treat_merge = merge_samples(meta_merge, sample(meta_merge)$treatment) 
# error - Error in x[sample.int(length(x), size, replace, prob)] : 
  #object of type 'S4' is not subsettable
otu_table(treat_merge)[1:5,1:5]
```

```{r Bacteria Indicator Species}
#This produces a text file with otus for groups and p values
#i <- interaction(new.data$treatment, new.data$month)
new.data <-cbind(meta,otu.2.rel)
library("labdsv")
###treatment and month? 

design.type <- new.data$treatment
dataREL.2013 <- new.data[,-c(1:5)]
#head(dataREL.2013)
set.seed(42)
dataREL <- dataREL.2013[, colSums(dataREL.2013) > 0.05]
bac.ind <- indval(dataREL, clustering =  design.type, numitr=1000, set.seed(42))
levels(design.type)
design.type
summary(bac.ind)

inds <- which(bac.ind$pval <= 0.05)
bac.indicators <- as.data.frame(matrix(NA, nrow = length(inds), ncol = 4))
colnames(bac.indicators) <- c("OTU", "Cluster", "IndVal", "Prob")

bac.indicators$OTU <- names(inds)
bac.indicators$Cluster <- bac.ind$maxcls[inds]
bac.indicators$IndVal <- bac.ind$indcls[inds]
bac.indicators$Prob <- bac.ind$pval[inds]

#need tax data

otu.tax<-as.data.frame(tax)
suffix<- 1:nrow(otu.tax)
ps <- sprintf("Otu%05d",suffix)
otu.tax$OTU<-ps

ind.tax <- otu.tax[which(as.character(otu.tax$OTU) %in% bac.indicators$OTU), ]
ind.tax <- ind.tax[match(ind.tax$OTU, bac.indicators$OTU), ]

indicator.bac <- cbind(bac.indicators, ind.tax[, -c(1)])

indicator.bac <- indicator.bac[order(as.numeric(indicator.bac$Cluster)), ]

table(indicator.bac$Cluster)
table(indicator.bac$Phylum)
table(indicator.bac$Cluster)
levels(design.type)

# Export Bacteria Indicator Table
write.table(indicator.bac, "../figures/BacterialIndicators_treatment.txt",
            sep="\t", row.names = F, quote = F)

#From what I can tell by comparing both methods of indicator analysis the second "cluster" 1, 2, 3, ... is the design.type in alphabetical order. So 1 = avM, 2 = avMF, 3 = bulkM, 4 = bulkMF, 5 = ecM, 6=ecMF
  
```

```{r phyloseq Phylum stacked graphs of taxa composition}

# melt to long format (for ggploting) 
# prune out phyla below 2% in each sample
wrc_phylum <- treat_merge %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.01) %>%                        # Filter out low abundance taxa
  arrange(Phylum)                                      # Sort data frame alphabetically by phylum

# Set colors for plotting
phylum_colors <- c("brown","orange", "blue", "red","yellow","purple")
  
  #c("#CBD588", "#5F7FC7","#DA5724", "#508578", "#CD9BCD",
  # "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
  #"#8569D5", "#5E738F","#D1A33D", "#8A7C64", "#599861", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Plot 
#s <- as.factor(wrc_phylum$Sample)
#wrc_phylum$Sample <- ordered(s,levels=c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"))
#s <- revalue(s, c("bulkM"="bulk unfertilized", "avM"="grass unfertilized", "ecM"="forb unfertilized","bulkMF"="bulk fertilized", "avMF"="grass fertilized", "ecMF"="forb fertilized"))
#s <- mapvalues(s, from = c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"), to = c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))

wrc_plot<- ggplot(wrc_phylum, aes(x = Phylum, y = Abundance, fill = as.factor(treatment))) + 
  #facet_grid(Type ~ .) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = phylum_colors) +
  # Remove x axis title
  theme(axis.title.x = element_blank()) + 
  guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance (Phyla > 1.0%) \n") +
  ggtitle("Phylum Composition of Bacterial Communities By Site") 

wrc_plot + coord_flip()

ggsave(file="../figures/phylum_stack.pdf", width=9, height=9, dpi=300)

```

```{r phyloseq Class stacked graphs of taxa composition}
# melt to long format (for ggploting) 
# prune out phyla below 2% in each sample
wrc_class <- treat_merge %>%
  tax_glom(taxrank = "Class") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.01) %>%                        # Filter out low abundance taxa
  arrange(Class)                                     # Sort data frame alphabetically by phylum

wrc_class
# Set colors for plotting
class_colors <- c("brown","orange", "blue", "red","yellow","purple")
  #c(
  #"#CBD588", "#5F7FC7","#DA5724", "#508578", "#CD9BCD",
  # "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
  #"#8569D5", "#5E738F","#D1A33D", "#8A7C64", "#599861", "#000000", "#E69F00", "#56B4E9", #"#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "green", "red", "yellow","tan", #"pink", "purple", "gray", "white", "339900","666699","996699","009966")

# Plot 

#s <- as.factor(wrc_class$Sample)
#wrc_class$Sample <- ordered(s,levels=c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"))
#t <- as.factor(wrc_class$plant)
#wrc_class$plant <- ordered(t, levels=c("1","2","3"))
#u <- as.factor(wrc_class$Treatment)
#wrc_class$Treatment <- ordered(u, levels=c("1","2"))

#t <- revalue(s, c("bulkM"="bulk unfertilized", "avM"="grass unfertilized", "ecM"="forb unfertilized","bulkMF"="bulk fertilized", "avMF"="grass fertilized", "ecMF"="forb fertilized"))
#t <- mapvalues(s, from = c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"), to = c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))
#t<-ordered(t,levels=c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))


wrc_plot<- ggplot(wrc_class, aes(x = Class, y = Abundance, fill = as.factor(treatment))) + 
  #facet_grid(plant ~ .) + 
  geom_bar(stat = "identity", width=0.5) + #scale_fill_manual(values=c("#111111","#777777"))+
  scale_fill_manual(values = class_colors) +
  # Remove x axis title
 theme_bw()  +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.title.y=element_text(margin=margin(r=10)), 
          axis.title.x=element_text(margin=margin(t=10)), panel.border =
          element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
  #theme(axis.title=element_text(vjust=1,size=14,face="bold"),
  #        axis.text=element_text(size=14), axis.text.x = element_text(size=14))+
  ylab("Class Relative Abundance > 1.0%") +
  xlab("Treatment") +
  labs(fill="Treatment") +
  ggtitle("Class Composition of Bacterial Communities") 

wrc_plot + coord_flip() 

ggsave(file="../figures/class_stack.pdf", width=9, height=9, dpi=300)

wrc_class_o<-wrc_class[,c(2:3,23:25)]

write.csv(wrc_class_o, file="class_composition.csv", row.names=TRUE)
```

```{r phyloseq Family stacked graphs of taxa composition}
# melt to long format (for ggploting) 
# prune out phyla below 1% in each sample
wrc_family <- treat_merge %>%
  tax_glom(taxrank = "Family") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.01)%>%#, Class == "Actinobacteria") %>%                        # Filter out low abundance taxa
  arrange(Family)                                     # Sort data frame alphabetically by phylum

# wrc_family
# Set colors for plotting
family_colors <- c("brown","orange", "blue", "red","yellow","purple")
  #"#CBD588", "#5F7FC7","#DA5724", "#508578", "#CD9BCD",
  # "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
 #"#8569D5", "#5E738F","#D1A33D", "#8A7C64", "#599861", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "green", "red", "yellow","tan", "pink", "purple", "gray", "white", "339900","666699","996699","black"
#)

# Plot 

#s <- as.factor(wrc_family$Sample)
#t <- revalue(s, c("bulkM"="bulk unfertilized", "avM"="grass unfertilized", "ecM"="forb unfertilized","bulkMF"="bulk fertilized", "avMF"="grass fertilized", "ecMF"="forb fertilized"))
#t <- mapvalues(s, from = c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"), to = c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))
#t<-ordered(t,levels=c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))

wrc_plot<- ggplot(wrc_family, aes(x = Family, y = Abundance, fill = as.factor(treatment))) + 
  #facet_grid(Type ~ .) +
  geom_bar(stat = "identity", width=0.5) +
  scale_fill_manual(values = family_colors) +
  # Remove x axis title
  theme_bw()  +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.title.y=element_text(margin=margin(r=10)), 
          axis.title.x=element_text(margin=margin(t=10)), panel.border =
          element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
  guides(fill = guide_legend(keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance > 1%") +
  xlab("Family Name")+
  labs(fill="Treatment")+
  ggtitle("Family Composition of Bacterial Communities") 

wrc_plot + coord_flip() 

wrc_family_o<-wrc_family[,c(2:3,40:45)]

write.csv(wrc_family_o, file="family_composition.csv", row.names=TRUE)

ggsave(file="../figures/family_stack.pdf", width=15, height=9, dpi=300)

```

```{r phyloseq Family stacked graphs of taxa composition}
# melt to long format (for ggploting) 
# prune out phyla below 1% in each sample
wrc_family <- treat_merge %>%
  tax_glom(taxrank = "Family") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.005, Class == "Alphaproteobacteria") %>%                        # Filter out low abundance taxa
  arrange(Family)                                     # Sort data frame alphabetically by phylum

# wrc_family
# Set colors for plotting
family_colors <- c("brown","orange", "blue", "red","yellow","purple")
  #"#CBD588", "#5F7FC7","#DA5724", "#508578", "#CD9BCD",
  # "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
 #"#8569D5", "#5E738F","#D1A33D", "#8A7C64", "#599861", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "green", "red", "yellow","tan", "pink", "purple", "gray", "white", "339900","666699","996699","black"
#)

# Plot 

#s <- as.factor(wrc_family$Sample)
#t <- revalue(s, c("bulkM"="bulk unfertilized", "avM"="grass unfertilized", "ecM"="forb unfertilized","bulkMF"="bulk fertilized", "avMF"="grass fertilized", "ecMF"="forb fertilized"))
#t <- mapvalues(s, from = c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"), to = c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))
#t<-ordered(t,levels=c("bulk unfertilized","grass unfertilized", "forb unfertilized","bulk fertilized", "grass fertilized", "forb fertilized"))

wrc_plot<- ggplot(wrc_family, aes(x = Family, y = Abundance, fill = as.factor(treatment))) + 
  #facet_grid(Type ~ .) +
  geom_bar(stat = "identity", width=0.5) +
  scale_fill_manual(values = family_colors) +
  # Remove x axis title
  theme_bw()  +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.title.y=element_text(margin=margin(r=10)), 
          axis.title.x=element_text(margin=margin(t=10)), panel.border =
          element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
  guides(fill = guide_legend(keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance > 1%") +
  xlab("Family Name")+
  labs(fill="Treatment")+
  ggtitle("Alphproteobacteria Composition of Bacterial Communities") 

wrc_plot + coord_flip() 

wrc_family_o<-wrc_family[,c(2:3,40:45)]

write.csv(wrc_family_o, file="family_composition.csv", row.names=TRUE)

ggsave(file="../figures/family_stack.pdf", width=15, height=9, dpi=300)

```


```{r phyloseq Genus stacked graphs of taxa composition}
# melt to long format (for ggploting) 
# prune out phyla below 2% in each sample
wrc_family <- treat_merge %>%
  tax_glom(taxrank = "Genus") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.01) %>%                        # Filter out low abundance taxa
  arrange(Genus)                                     # Sort data frame alphabetically by phylum

 wrc_family
# Set colors for plotting
family_colors <- c(
  "#CBD588", "#5F7FC7","#DA5724", "#508578", "#CD9BCD",
   "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
  "#8569D5", "#5E738F","#D1A33D", "#8A7C64", "#599861", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "green", "red", "yellow","tan", "pink", "purple", "gray", "white", "339900","666699","black"
)

# Plot 

#s <- as.factor(wrc_family$Sample)
#wrc_family$Sample <- ordered(s,levels=c("bulkM","avM", "ecM","bulkMF","avMF", "ecMF"))

wrc_plot<- ggplot(wrc_family, aes(x = Genus, y = Abundance, fill = as.factor(treatment))) + 
  #facet_grid(Type ~ .) +
  geom_bar(stat = "identity", width=0.5) +
  scale_fill_manual(values = family_colors) +
  # Remove x axis title
  theme(axis.title.x = element_blank()) + 
  guides(fill = guide_legend(keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance (Genus > 1%) \n") +
  ggtitle("Genus Composition of Bacterial Communities By Site") 

wrc_plot + coord_flip() 
ggsave(file="../figures/genus_stack.1.pdf", width=15, height=9, dpi=300)
```


```{r ch4co2eq  by season, echo=T, out.width="100%"}

### This is where I stopped at

i <- with(ghg, interaction(hydrology,season))
#linear model for nitrous oxide
ghg.lm <- lm(ch4co2eq~hydrology+season+i,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

t <- HSD.test(ghg.lm, "season", group=TRUE, alpha=.05)
t

p <- ggplot(ghg, aes(x=season, y=ch4co2eq, color=as.factor(hydrology), shape=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = c("PI", "SL"))  #scale_shape_manual(name="Hydrology", values=c(17,16), labels = c("PI", "SL")) + #scale_x_discrete(labels=c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter"), limits=c("sp", "sm", "f", "w"))

p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=20), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Season", y = (expression(paste("Ch4 CO2 eq")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/ch4co2Season.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)


```

```{r n20co2eq  by season, echo=T, out.width="100%"}
#linear model for nitrous oxide
ghg.lm <- lm(n2oco2eq~hydrology*season,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

anova2<-(aov(n2oco2eq~as.factor(season)*as.factor(hydrology),data=ghg))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p <- ggplot(ghg, aes(x=season, y=n2oco2eq, color=as.factor(hydrology), shape=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = c("PI", "SL")) + scale_shape_manual(name="Hydrology", values=c(17,16), labels = c("PI", "SL")) + scale_x_discrete(labels=c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter"), limits=c("sp", "sm", "f", "w"))

p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=20), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Season", y = (expression(paste("n2o CO2 eq")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/n2oco2Season.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/n2oco2Season.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r Ch4 by sample plot, echo=T, out.width="100%"}
#linear model for methane by plot
ghg.lm <- lm(ch4cmgm2hr~hydrology*season,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

ghg$facet=factor(ghg$season, levels=c("sp","sm","f","w"))

p <- ggplot(ghg, aes(x=sample, y=ch4cmgm2hr, color=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=0.75, position=position_dodge(width=0.3)) + scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = c("PI", "SL")) + scale_shape_manual(name="Hydrology", values=c(17,16), labels = c("PI", "SL")) +facet_wrap(~season)
p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=8), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("CH"[4], " mg C m"^-{2}, " hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/CH4byPlot.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r CO2 by sample plot, echo=T, out.width="100%"}
#linear model for carbon dioxide by plot
ghg.lm <- lm(co2mgm2hr~hydrology*season,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

p <- ggplot(ghg, aes(x=sample, y=co2mgm2hr, color=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=0.75, position=position_dodge(width=0.3)) + scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = c("PI", "SL")) + scale_shape_manual(name="Hydrology", values=c(17,16), labels = c("PI", "SL")) +facet_wrap(~season) 
p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=8), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("CO"[2], " (mg C m"^-{2}," hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/CO2byPlot.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r N2O by sample plot, echo=T, out.width="100%"}
#linear model for nitrous oxide by plot
ghg.lm <- lm(n2omgm2hr~hydrology*season,data=ghg)
plot(ghg.lm)
anova(ghg.lm)

p <- ggplot(ghg, aes(x=sample, y=n2omgm2hr, color=as.factor(hydrology))) + stat_summary(fun.data=mean_cl_boot,size=0.75, position=position_dodge(width=0.3)) + scale_color_manual(name="Hydrology", values=c("navy","darkgreen"), labels = c("PI", "SL")) + scale_shape_manual(name="Hydrology", values=c(17,16), labels = c("PI", "SL")) +facet_wrap(~season)
p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=8), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("N"[2],"O (mg N m"^-{2}," hr"^-{1},")")))) + theme(strip.text.x = element_text(size=16, face="bold"), strip.text.y = element_text(size=16, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/N2ObyPlot.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r water quality, echo=T, out.width="100%"}
#water data
water <-read.csv("../data/CSW_Water_Nutes.csv")
water<-water %>% filter(plot!="5-South Inlet", Station != "CSW_007", Station!="CSW_012") %>%
mutate(NO3.NO2.1 = ifelse(NO3.NO2.1 < 0 , 0, NO3.NO2.1))
```

```{r water NH4.1 = NH4 mg/l}
water.lm <- lm(NH4.1~plot+season,data=water)
plot(water.lm)
anova(water.lm)
summary(water.lm)

posthoc <- HSD.test(water.lm, "plot", group=T)
posthoc$groups

anova2<-(aov(NH4.1~as.factor(plot)+as.factor(season),data=water))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(water, aes(x=plot, y=NH4.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("NH"[4], " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/nh4.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r water:NO3+NO2. = NO3 + NO2 mg/L}
water.lm <- lm(NO3.NO2.1~plot+ season,data=water)
plot(water.lm)
anova(water.lm)
summary(water.lm)

posthoc <- HSD.test(water.lm, "season", group=T)
posthoc$groups

anova2<-(aov(NH4.1~as.factor(plot)+as.factor(season),data=water))
#car::Anova(anova2, type="III")
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p2 <- ggplot(water, aes(x=plot, y=NO3.NO2.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p2 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("NO"[3],"+NO"[2], " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/no3.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r water: PO4.1 = phosphate mg/L}
water.lm <- lm(PO4.1~plot+season,data=water)
plot(water.lm)
anova(water.lm)
summary(water.lm)

posthoc <- HSD.test(water.lm, "season", group=T)
posthoc$groups

anova2<-(aov(PO4.1~as.factor(plot)+as.factor(season),data=water))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p6 <- ggplot(water, aes(x=plot, y=PO4.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p6 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("PO"[4], " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/po4.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r water: CL.1 = Chloride mg/L}
water.lm <- lm(CL.1~plot+season,data=water)
plot(water.lm)
anova(water.lm)
summary(water.lm)

p8 <- ggplot(water, aes(x=plot, y=CL.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p8 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("Cl mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/cl.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)

library(grid)
grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(p6), ggplotGrob(p8),  size = "last"))
```

```{r water: DKN, PN, PP, TDP}

water.lm <- lm(DKN.1~season,data=water)
plot(water.lm)
anova(water.lm)

water.lm <- lm(PN.1~season,data=water)
plot(water.lm)
anova(water.lm)

water.lm <- lm(PP.1~season,data=water)
plot(water.lm)
anova(water.lm)

water.lm <- lm(TDP.1~season,data=water)
plot(water.lm)
anova(water.lm)

#Only have for a couple of months... don't think they were run but should verify
#p3 <- ggplot(water, aes(x=plot, y=DKN.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

#p3 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("Dissolved N"[4], " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

#ggsave("../figures/DKN.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)

p4 <- ggplot(water, aes(x=plot, y=PN.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p4 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("PN mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/pn.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)


p5 <- ggplot(water, aes(x=plot, y=PP.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p5 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("PP mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/pp.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)


p7 <- ggplot(water, aes(x=plot, y=TDP.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p7 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Sample Location", y = (expression(paste("TDP mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/tdp.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r soil temp}
s <- ggplot(ghg, aes(x = season , y =temp)) + 
  geom_boxplot(aes(color=season), lwd=1)
s + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "blue"), labels = c("spring", "summer","fall","winter"))  + scale_x_discrete(labels=c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter"), limits=c("sp", "sm", "f", "w")) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Season", y = (expression(paste('Soil Temperature (',~degree,'C)',sep='')))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=1))

ggsave("../figures/SoilTemp.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r moist.percent = soil moisture}
soil.lm <- lm(moist.percent~hydrology+season,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(moist.percent~as.factor(hydrology),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=moist.percent, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("Soil Moisture (%)")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/SoilMoisture.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/SoilMoisture.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r soil pH}
soil.lm <- lm(ph~hydrology,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(ph~as.factor(hydrology),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=ph, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("pH")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/pH.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r soil om.percent}
soil.lm <- lm(om.percent~hydrology+season,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(om.percent~as.factor(hydrology),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=om.percent, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("Soil Organic Matter (%)")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/SOM.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r soil cn}
soil.lm <- lm(c.n~hydrology+season,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(c.n~as.factor(hydrology),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=c.n, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("Soil C/N ratio (wt/wt)")))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/SoilCN.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r soil NH4}

soil.lm <- lm(nh4.mgn.l.1~hydrology+season,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(nh4.mgn.l.1~as.factor(hydrology),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=nh4.mgn.l.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("NH"[4], " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/SoilNH4.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/SoilNH4.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r soil NO3}
soil.lm <- lm(no3.mgn.l.1~hydrology+season,data=design)
plot(soil.lm)
anova(soil.lm)
summary(soil.lm)

posthoc <- HSD.test(soil.lm, "hydrology", group=T)
posthoc$groups

anova2<-(aov(no3.mgn.l.1~as.factor(hydrology)+as.factor(season),data=design))
posthoc <- TukeyHSD(anova2, group=T)
posthoc

p1 <- ggplot(design, aes(x=hydrology, y=no3.mgn.l.1, color=as.factor(season), shape=as.factor(season))) + stat_summary(fun.data=mean_cl_boot,size=1.25, position=position_dodge(width=0.5)) + scale_color_manual(name="Season", values=c("darkgreen","red", "orange", "navy"), labels = c("spring", "summer","fall","winter")) + scale_shape_manual(name="Season", values=c(15,16,17,18), labels = c("spring", "summer","fall","winter"))

p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=20,face="bold"), axis.text=element_text(size=20), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, size=16), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + labs(x = "Hydrology", y = (expression(paste("NO"[3],, " mg L"^-{1})))) + theme(strip.text.x = element_text(size=20, face="bold"), strip.text.y = element_text(size=20, face="bold"), strip.background = element_rect(colour="black", fill="white", size=3))

ggsave("../figures/SoilNO3.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/SoilNO3.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r CO2 equivalents}
#This is the annual amount of C stored or released from PI or SL plots yearly
#First get average of all plots by hyrdology and season in mg C m2 hr
ghg.co2.equiv <- ghg %>% 
  filter(month=="5-May"| month=="7-Jul" |month == "10-Oct"| month=="12-Dec")%>%
  mutate(co2cgm2hr=co2cgm2day/24)
#%>%
#  group_by(hydrology, month) %>%
#  summarise(mch4mgm2hr=mean(ch4cmgm2hr),mco2mgm2hr=mean(co2cmgm2hr),mn2omgm2hr=mean(n2onmgm2hr)) %>%
  #Then multiple mg C m2 hr * 24 * 365 = mg C m2 yr
#  mutate(ch4mgcm2yr = mch4mgm2hr * 8760/1000/1000, co2mgcm2yr = mco2mgm2hr*8760/1000/1000, n2omgnm2yr=mn2omgm2hr*8760/1000/1000) %>%
#  mutate(ch4mgcyr=0, co2mgcyr=0, n2omgnyr=0)%>%
 #Then multiple each gas (ch4mgcyrco2, n2omgnyrco2, co2mgcyr) 
  #by percent PI (65%) and percent SL (35%) of 5600sq ft converted to m2 (520...)
#  mutate(ch4mgcyr=ifelse(hydrology=="PI", ch4mgcm2yr*338.167, ch4mgcm2yr * 182.09)) %>% mutate(co2mgcyr=ifelse(hydrology=="PI", co2mgcm2yr*338.167, co2mgcm2yr * 182.09)) %>% mutate(n2omgnyr=ifelse(hydrology=="PI", n2omgnm2yr*338.167, n2omgnm2yr * 182.09))%>%
  #Take that amount of mg C yr and multiple by CO2 Equivalents
  
  ####change to mg m2 hr....
#  mutate(ch4mgcyrco2 = ch4mgcyr*25, n2omgnyrco2=n2omgnyr *298)
  
g <- ghg.co2.equiv %>%
   group_by(hydrology, month) %>%
  summarise(mch4co2=mean(ch4co2eq), mco2 = mean(co2cmgm2hr), mn2oco2 = mean(n2oco2eq))
 

require(tidyr)
#####Change this to mch4mgm3hr... 
wide_to_long <- gather(g, co2eq, measurement, mch4co2, mco2, mn2oco2, factor_key=TRUE)  #ch4mgcyrco2, co2mgcyr, n2omgnyrco2, factor_key=TRUE)
wide_to_long

totc <- summarise(wide_to_long, s = sum(measurement))
totc$s
#PI 98.86%
#8958
#SL 1.14%
#104
#Total C in = 9071 kg C year


levels(wide_to_long$hydrology) 
levels(wide_to_long$hydrology) <- c("PI","SL")

p <-ggplot(wide_to_long, aes(x=month, y=measurement, fill=co2eq)) + geom_bar(stat="identity") + facet_wrap(~hydrology) +
  scale_x_discrete(labels=c("May", "Jul", "Oct", "Dec"), limits=c("5-May","7-Jul","10-Oct","12-Dec"))# + scale_x_discrete(labels=c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter"), limits=c("sp", "sm", "f", "w")) + labs(x = "Season", y = (expression(paste("Total Annual Carbon (kg)")))) 

p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + theme(strip.text.x = element_text(size=16), strip.text.y = element_text(size=16), strip.background = element_rect(colour="black", fill="white", size=1)) + scale_fill_manual(values=c("navy","darkgreen", "orange"))+labs(x = "", y = (expression(paste("C mg m"^-{2}, "hr"^{-1}))))

ggsave("../figures/CO2equiv_mean_mg.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/CO2equiv_mean_mg.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=8, height=4, dpi=300, limitsize=TRUE)

ghg.co2.equiv.sl <- wide_to_long %>%
  filter(hydrology == "SL")

p <-ggplot(ghg.co2.equiv.sl, aes(x=month, y=measurement, fill=co2eq)) + geom_bar(stat="identity") + facet_wrap(~hydrology) + 
  scale_x_discrete(labels=c("May", "Jul", "Oct", "Dec"), limits=c("5-May","7-Jul","10-Oct","12-Dec"))+
  #scale_x_discrete(labels=c("sp" = "spring", "sm" = "summer", "f" = "fall", "w" = "winter"), limits=c("sp", "sm", "f", "w")) + 
  labs(x = "", y = (expression(paste("C mg m"^-{2}, "hr"^{-1})))) #ng N"[2],"O g"^-{1}

p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16), axis.text=element_text(size=16), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1)) + theme(axis.ticks.length=unit(0.3,"cm")) + theme(strip.text.x = element_text(size=16), strip.text.y = element_text(size=16), strip.background = element_rect(colour="black", fill="white", size=1)) + scale_fill_manual(values=c("navy","darkgreen", "orange"))

ggsave("../figures/CO2equiv_JustSL_mean_mg.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

ggsave("../figures/CO2equiv_JustSL_mean_mg.jpeg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=8, height=4, dpi=300, limitsize=TRUE)
```

